[package]

name = "snowmew"
version = "0.1.0"
authors = [
    "Colin Sherratt <colin.sherratt@gmail.com>",
]

license = "Apache-2.0"
description = "A game engine"
homepage = "https://github.com/csherratt/snowmew"
repository = "https://github.com/csherratt/snowmew"


[lib]
name = "snowmew"
path = "src/snowmew.rs"

[dependencies.snowmew-core]
path = "src/snowmew-core/"

[dependencies.snowmew-graphics]
path = "src/snowmew-graphics/"

[dependencies.snowmew-position]
path = "src/snowmew-position/"

[dependencies.snowmew-render]
path = "src/snowmew-render/"

[dependencies.snowmew-render-gfx]
path = "src/snowmew-render-gfx/"

[dependencies.snowmew-render-mux]
path = "src/snowmew-render-mux/"

[dependencies.snowmew-loader]
path = "src/snowmew-loader/"

[dependencies]
time = "*"

[[example]]
name = "cubes"
path = "examples/cubes/main.rs"

[[example]]
name = "gears"
path = "examples/gears/main.rs"

[[example]]
name = "noclip"
path = "examples/noclip/main.rs"
