[package]

name = "snowmew-graphics"
version = "0.1.0"
authors = [
    "Colin Sherratt <colin.sherratt@gmail.com>",
]

[lib]
name = "snowmew-graphics"
path = "lib.rs"

[dependencies.collision]
git = "https://github.com/csherratt/collision-rs.git"

[dependencies.snowmew-core]
path = "../snowmew-core/"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs.git"

[dependencies.stb_image]
git = "https://github.com/csherratt/rust-stb-image.git"

[dependencies.gfx]
git = "https://github.com/csherratt/gfx-rs"

[dependencies]
genmesh = "*"
