[package]
name = "snowmew-core"
version = "0.0.1"
authors = [
    "Colin Sherratt <colin.sherratt@gmail.com>",
]
license="Apache 2"
homepage="https://github.com/csherratt/snowmew"
description="The core of the Snowmew engine"

[lib]
name = "snowmew-core"
path = "lib.rs"

[dependencies]
time = "*"
rustc-serialize="*"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.nice_glfw]
git = "https://github.com/csherratt/nice_glfw.git"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs.git"

[dependencies.cow]
git = "https://github.com/csherratt/cow-rs.git"

[dependencies.opencl]
git = "https://github.com/csherratt/rust-opencl.git"

[dependencies.ovr]
git = "https://github.com/csherratt/vr-rs.git"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.device]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.collect]
git = "https://github.com/csherratt/collect-rs"
branch = "cow_trie"
